import React from "react";
import * as Icon from "react-feather";

const PrivacyPolicy = () => {
    return (
        <div class="content">
            <div class="flex items-center justify-around mt-10">
                <div class="intro-y col-span-12 lg:col-span-6 box py-10 border-2 border-primary dark:border-primary min-w-[428px]">
                    <Icon.Lock className="block w-12 h-12 text-primary mx-auto" />
                    <div class="font-medium text-center text-base mt-3">Privacy Policy</div>
                </div>
                <div class="intro-y col-span-12 lg:col-span-6 box py-10 min-w-[428px]">
                    <Icon.Shield className="block w-12 h-12 text-primary mx-auto" />
                    <div class="font-medium text-center text-base mt-3">Multi Application</div>
                </div>
            </div>
            <div class="grid grid-cols-12 gap-5 mt-5">
                <div class="intro-y col-span-12 lg:col-span-6">
                    <div class="box p-5">
                        <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                            I2PAY TECHNOLOGIES (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy
                            explains how your personal information is collected, used, and disclosed by I2PAY TECHNOLOGIES.
                            <br />
                            <br />
                            This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”)
                            alongside our application, I2PAY TECHNOLOGIES. By accessing or using our Service, you signify that you have
                            read, understood, and agree to our collection, storage, use, and disclosure of your personal information as
                            described in this Privacy Policy and our Terms of Service.
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Definitions and key terms</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are
                                referenced, are strictly defined as:
                            </div>
                            <ul className="list-disc ml-5 mt-3 text-slate-600 dark:text-slate-500">
                                <li className="mt-2">
                                    Cookie: small amount of data generated by a website and saved by your web browser. It is used to
                                    identify your browser, provide analytics, remember information about you such as your language
                                    preference or login information.
                                </li>
                                <li className="mt-2">
                                    Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to I2PAY TECHNOLOGIES
                                    PRIVATE LIMITED, (SHOP NO. UG-06 TO UG-17 SWARN PLAZA SECTOR SWARN NAGRI NOIDA Gautam Buddha Nagar UP
                                    201310), that is responsible for your information under this Privacy Policy.
                                </li>
                                <li className="mt-2">
                                    Country: where I2PAY TECHNOLOGIES or the owners/founders of I2PAY TECHNOLOGIES are based, in
                                    this case is India
                                </li>
                                <li className="mt-2">
                                    Customer: refers to the company, organization or person that signs up to use the I2PAY TECHNOLOGIES
                                    Service to manage the relationships with your consumers or service users.
                                </li>
                                <li className="mt-2">
                                    Device: any internet connected device such as a phone, tablet, computer or any other device that can be
                                    used to visit I2PAY TECHNOLOGIES and use the services.
                                </li>
                                <li className="mt-2">
                                    IP address: Every device connected to the Internet is assigned a number known as an Internet protocol
                                    (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used
                                    to identify the location from which a device is connecting to the Internet.
                                </li>
                                <li className="mt-2">
                                    Personnel: refers to those individuals who are employed by I2PAY TECHNOLOGIES or are under contract
                                    to perform a service on behalf of one of the parties.
                                </li>
                                <li className="mt-2">
                                    Personal Data: any information that directly, indirectly, or in connection with other information —
                                    including a personal identification number — allows for the identification or identifiability of a
                                    natural person.
                                </li>
                                <li className="mt-2">
                                    Service: refers to the service provided by I2PAY TECHNOLOGIES as described in the relative terms (if
                                    available) and on this platform.
                                </li>
                                <li className="mt-2">
                                    Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and
                                    others who provide our content or whose products or services we think may interest you.
                                </li>
                                <li className="mt-2">
                                    Website: I2PAY TECHNOLOGIES’s site, which can be accessed via this URL: https://I2PAY.com/
                                </li>
                                <li className="mt-2">
                                    You: a person or entity that is registered with I2PAY TECHNOLOGIES to use the Services.
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Information automatically collected</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                There is some information like your Internet Protocol (IP) address and/or browser and device characteristics
                                — is collected automatically when you visit our platform. This information may be used to connect your
                                computer to the Internet. Other information collected automatically could be a login, e-mail address,
                                password, computer and connection information such as browser plug-in types and versions and time zone
                                setting, operating systems and platforms, purchase history, (we sometimes aggregate with similar information
                                from other Users), the full Uniform Resource Locator (URL) clickstream to, through and from our Website that
                                may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number
                                you used to call our Customer Services. We may also use browser data such as cookies, Flash cookies (also
                                known as Flash Local Shared Objects) or similar data on certain parts of our Website for fraud prevention
                                and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect
                                session information including page response times, download errors, length of visits to certain pages, page
                                interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from
                                the page. We may also collect technical information to help us identify your device for fraud prevention and
                                diagnostic purposes.
                                <br />
                                <br />
                                We automatically collect certain information when you visit, use or navigate the platform. This information
                                does not reveal your specific identity (like your name or contact information) but may include device and
                                usage information, such as your IP address, browser and device characteristics, operating system, language
                                preferences, referring URLs, device name, country, location, information about who and when you use our and
                                other technical information. This information is primarily needed to maintain the security and operation of
                                our platform, and for our internal analytics and reporting purposes.
                            </div>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Personnel</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                If you are a I2PAY TECHNOLOGIES worker or applicant, we collect information you voluntarily provide to
                                us. We use the information collected for Human Resources purposes in order to administer benefits to workers
                                and screen applicants.
                                <br />
                                <br />
                                You may contact us in order to (1) update or correct your information, (2) change your preferences with
                                respect to communications and other information you receive from us, or (3) receive a record of the
                                information we have relating to you. Such updates, corrections, changes and deletions will have no effect on
                                other information that we maintain, or information that we have provided to third parties in accordance with
                                this Privacy Policy prior to such update, correction, change or deletion.
                            </div>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Sale of Business</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                We reserve the right to transfer information to a third party in the event of a sale, merger or other
                                transfer of all or substantially all of the assets of I2PAY TECHNOLOGIES or any of its Corporate
                                Affiliates (as defined herein), or that portion of I2PAY TECHNOLOGIES or any of its Corporate Affiliates
                                to which the Service relates, or in the event that we discontinue our business or file a petition or have
                                filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third
                                party agrees to adhere to the terms of this Privacy Policy.
                            </div>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Affiliates</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                We may disclose information (including personal information) about you to our Corporate Affiliates. For
                                purposes of this Privacy Policy, “Corporate Affiliate” means any person or entity which directly or
                                indirectly controls, is controlled by or is under common control with I2PAY TECHNOLOGIES, whether by
                                ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be
                                treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
                            </div>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Governing Law</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                This Privacy Policy is governed by the laws of India without regard to its conflict of laws provision. You
                                consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between
                                the parties under or in connection with this Privacy Policy except for those individuals who may have rights
                                to make claims under Privacy Shield, or the Swiss-US framework.
                                <br />
                                <br />
                                The laws of India, excluding its conflicts of law rules, shall govern this Agreement and your use of the
                                website. Your use of the website may also be subject to other local, state, national, or international laws.
                                <br />
                                <br />
                                By using I2PAY TECHNOLOGIES or contacting us directly, you signify your acceptance of this Privacy
                                Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our
                                services. Continued use of the website, direct engagement with us, or following the posting of changes to
                                this Privacy Policy that do not significantly affect the use or disclosure of your personal information will
                                mean that you accept those changes.
                            </div>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Your Consent</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                We’ve updated our Privacy Policy to provide you with complete transparency into what is being set when you
                                visit our site and how it’s being used. By using our I2PAY TECHNOLOGIES, registering an account, or
                                making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
                            </div>
                        </div>
                    </div>
                    <div class="box mt-6">
                        <div class="flex items-center p-5 border-b border-slate-200/60 dark:border-darkmode-400">
                            <h2 class="font-medium text-base mr-auto">Links to Other Websites</h2>
                        </div>
                        <div className="p-5">
                            <div class="accordion-body text-slate-600 dark:text-slate-500 leading-relaxed">
                                This Privacy Policy applies only to the Services. The Services may contain links to other websites not
                                operated or controlled by I2PAY TECHNOLOGIES. We are not responsible for the content, accuracy or
                                opinions expressed in such websites, and such websites are not investigated, monitored or checked for
                                accuracy or completeness by us. Please remember that when you use a link to go from the Services to another
                                website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website,
                                including those that have a link on our platform, is subject to that website’s own rules and policies. Such
                                third parties may use their own cookies or other methods to collect information about you.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="intro-y col-span-12 lg:col-span-6">
                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
