export const GET_API_KEY_REQUEST = "GET_API_KEY_REQUEST";
export const GET_API_KEY_RESPONSE = "GET_API_KEY_RESPONSE";

export const ADD_API_KEY_REQUEST = "ADD_API_KEY_REQUEST";
export const ADD_API_KEY_RESPONSE = "ADD_API_KEY_RESPONSE";

export const DELETE_API_KEY_REQUEST = "DELETE_API_KEY_REQUEST";
export const DELETE_API_KEY_RESPONSE = "DELETE_API_KEY_RESPONSE";
