export const GET_CONNECTOR_REQUEST = "GET_CONNECTOR_REQUEST";
export const GET_CONNECTOR_RESPONSE = "GET_CONNECTOR_RESPONSE";

export const GET_CONNECTOR_SETTINGS_REQUEST = "GET_CONNECTOR_SETTINGS_REQUEST";
export const GET_CONNECTOR_SETTINGS_RESPONSE = "GET_CONNECTOR_SETTINGS_RESPONSE";

export const UPDATE_CONNECTOR_REQUEST = "UPDATE_CONNECTOR_REQUEST";
export const UPDATE_CONNECTOR_RESPONSE = "UPDATE_CONNECTOR_RESPONSE";

export const UPDATE_CONNECTOR_SETTINGS_REQUEST = "UPDATE_CONNECTOR_SETTINGS_REQUEST";
export const UPDATE_CONNECTOR_SETTINGS_RESPONSE = "UPDATE_CONNECTOR_SETTINGS_RESPONSE";

export const GET_ENABLED_CONNECTOR_REQUEST = "GET_ENABLED_CONNECTOR_REQUEST";
export const GET_ENABLED_CONNECTOR_RESPONSE = "GET_ENABLED_CONNECTOR_RESPONSE";

export const UPDATE_CONNECTOR_MODE_REQUEST = "UPDATE_CONNECTOR_MODE_REQUEST";
export const UPDATE_CONNECTOR_MODE_RESPONSE = "UPDATE_CONNECTOR_MODE_RESPONSE";

export const getConnectorsRequest = (searchQuery, callback) => ({
    type: GET_CONNECTOR_REQUEST,
    searchQuery,
    callback,
});

export const getConnectorsResponse = (data) => ({
    type: GET_CONNECTOR_RESPONSE,
    payload: data,
});
