export const SET_MENU_TYPE_REQUEST = "SET_MENU_TYPE_REQUEST";
export const SET_MENU_TYPE_RESPONSE = "SET_MENU_TYPE_RESPONSE";

export const SET_LISTING_TYPE_REQUEST = "SET_LISTING_TYPE_REQUEST";
export const SET_LISTING_TYPE_RESPONSE = "SET_LISTING_TYPE_RESPONSE";

export const SET_CURRENCY_TYPE_REQUEST = "SET_CURRENCY_TYPE_REQUEST";
export const SET_CURRENCY_TYPE_RESPONSE = "SET_CURRENCY_TYPE_RESPONSE";
