export const GET_PAYMENT_LINK_REQUEST = "GET_PAYMENT_LINK_REQUEST";
export const GET_PAYMENT_LINK_RESPONSE = "GET_PAYMENT_LINK_RESPONSE";

export const ADD_PAYMENT_LINK_REQUEST = "ADD_PAYMENT_LINK_REQUEST";
export const ADD_PAYMENT_LINK_RESPONSE = "ADD_PAYMENT_LINK_RESPONSE";

export const DELETE_PAYMENT_LINK_REQUEST = "DELETE_PAYMENT_LINK_REQUEST";
export const DELETE_PAYMENT_LINK_RESPONSE = "DELETE_PAYMENT_LINK_RESPONSE";

export const UPDATE_PAYMENT_LINK_REQUEST = "UPDATE_PAYMENT_LINK_REQUEST";
export const UPDATE_PAYMENT_LINK_RESPONSE = "UPDATE_PAYMENT_LINK_RESPONSE";

export const DETAIL_PAYMENT_LINK_REQUEST = "DETAIL_PAYMENT_LINK_REQUEST";
export const DETAIL_PAYMENT_LINK_RESPONSE = "DETAIL_PAYMENT_LINK_RESPONSE";

export const PAYMENT_LINK_SEND_REQUEST = "PAYMENT_LINK_SEND_REQUEST";
export const PAYMENT_LINK_SEND_RESPONSE = "PAYMENT_LINK_SEND_RESPONSE";

export const getPaymentLinkRequest = (currentPage, perPage, searchQuery, callback) => ({
    type: GET_PAYMENT_LINK_REQUEST,
    currentPage,
    perPage,
    searchQuery,
    callback,
});

export const getPaymentLinkResponse = (data) => ({
    type: GET_PAYMENT_LINK_RESPONSE,
    payload: data,
});
