export const PAYMENT_PAGE_1 = "";
export const PAYMENT_PAGE_2 =
    "<h2><strong>About the event</strong></h2><p># Add a description and highlights of the event</p><p>&nbsp;</p><h2><strong>Venue</strong></h2><p># Name of the venue for your event</p><p>&nbsp;</p><h2><strong>Starts at</strong></h2><p># Date and time of the start of the event</p><p>&nbsp;</p><h2><strong>Ends at</strong></h2><p># Date and time of the end of the event</p><p>&nbsp;</p><h2><strong>Image Gallery?</strong></h2><p># Select and upload some images for your event</p><p>&nbsp;</p><h2><strong>Organiser information</strong></h2><p># Organisation / organiser &nbsp;description with address and contact information</p><p>&nbsp;</p><h2><strong>Registration Details?</strong></h2><p># Information about passes / packages, website details</p>";
export const PAYMENT_PAGE_3 =
    "<h2><strong>Donation Cause</strong></h2><p># Provide information about your fundraising drive</p><p>&nbsp;</p><h2><strong>Campaign starts on</strong></h2><p># Date and time of the start of the drive</p><p>&nbsp;</p><h2><strong>Campaign ends on</strong></h2><p># Date and time of the end of the drive</p><p>&nbsp;</p><h2><strong>Organiser details</strong></h2><p># Organisation / Organiser description with address and contact information</p><p>&nbsp;</p><h2><strong>Tax exemption details</strong></h2><p># Details of tax exemption eligibility for donors</p><p>&nbsp;</p><h2><strong>Campaign images</strong></h2><p># Select and upload up to 4 images for fundraising drive</p>";
export const PAYMENT_PAGE_4 =
    "<h2><strong>Product Image(s)</strong></h2><p># Select and upload some images of your product / service</p><p>&nbsp;</p><h2><strong>Product Description</strong></h2><p># Add product description with features and benefits</p><p>&nbsp;</p><h2><strong>Ships in X days ( if physical product )</strong></h2><p># Time required to prepare order for shipment in days</p><p>&nbsp;</p><h2><strong>Average delivery time</strong></h2><p># Average time required for delivery after shipment</p>";
export const PAYMENT_PAGE_5 =
    "<h2><strong>Program name</strong></h2><p># Name of the course / workshop / membership</p><p>&nbsp;</p><h2><strong>Program Description</strong></h2><p># Course description with highlights and benefits to attendees</p><p>&nbsp;</p><h2><strong>Fee breakup</strong></h2><p># Fee structure for activities of the course / workshop / membership</p><p>&nbsp;</p><h2><strong>Name of the organiser</strong></h2><p># Organisation / Organiser description with address and contact information</p>";
