import * as Icon from "react-feather";
import Images from "../../assets/images";

export const MAX_FILE_LIMIT = 1;
export const TOTAL_MERCHANT_APPLICATION_STEP = 3;
export const GST_PERCENTAGE = [0, 5, 12, 18, 28];
export const menuElementsType = {
    SINGLE: "single",
    MULTI: "multi",
    NONE: "none",
};
export const specialRoutes = [
    {
        to: "/api-doc",
        header: true,
        menu: false,
        isAuthRequired: false,
    },
    {
        to: "/api-details",
        header: true,
        menu: false,
        isAuthRequired: false,
    },
    {
        to: "/notifications",
        header: true,
        menu: true,
        isAuthRequired: false,
    },

    // {
    //     to: "/thank-you",
    //     header: true,
    //     menu: true,
    //     isAuthRequired: true,
    // },
];

export const menuItems = [
    {
        id: 1,
        to: "/",
        totalRoute: ["/"],
        icon: () => <Icon.Home size={20} />,
        title: "Dashboard",
        type: menuElementsType.SINGLE,
        isAuthRequired: true,
        header: true,
        menu: true,
    },

    {
        id: 2,
        to: "/merchant-register",
        totalRoute: ["/merchant-register"],
        icon: () => <Icon.Layers size={20} />,
        title: "Application",
        type: menuElementsType.SINGLE,
        isAuthRequired: true,
        header: true,
        menu: true,
    },
    {
        id: 3,
        totalRoute: ["/connector", "/connector/:connector/settings", "/default-connector"],
        icon: () => <Icon.Link size={20} />,
        title: "Connectors",
        type: menuElementsType.MULTI,
        subMenuItems: [
            {
                id: 1,
                title: "Connector List",
                to: "/connector",
                icon: () => <Icon.Link size={20} />,
            },
            {
                id: 2,
                title: "Default Connector",
                to: "/default-connector",
                icon: () => <img src={Images.DefaultConnectors} />,
            },
        ],
        isAuthRequired: true,
        header: true,
        menu: true,
    },

    // test-transactions
    // {
    //     id: 4,
    //     to: "/transactions",
    //     totalRoute: ["/transactions"],
    //     icon: () => <Icon.Database />,
    //     title: "Transactions",
    //     type: menuElementsType.SINGLE,
    //     isAuthRequired: true,
    //     header: true,
    //     menu: true,
    // },
    {
        id: 4,
        icon: () => <Icon.Repeat size={20} />,
        title: "Transactions",
        // to: ["/pay-button-list", "/invoice", "/"],
        totalRoute: [
            "/transactions",
            "/live-transactions",
            "/test-transactions",
            "refund-transactions",
            "chargeback-transactions",
            "suspicious-transactions",
            "remove-suspicious-transactions",
        ],
        type: menuElementsType.MULTI,
        subMenuItems: [
            {
                id: 1,
                title: "Live Transactions",
                to: "/live-transactions",
                icon: () => <img alt="transaction-image" height="25" width="25" src={Images.LiveTransactions} />,
            },
            {
                id: 2,
                title: "Refund",
                to: "/refund-transactions",
                icon: () => <img alt="transaction-image" height="25" width="25" src={Images.Refund} />,
            },
            {
                id: 3,
                title: "Chargebacks",
                to: "/chargeback-transactions",
                icon: () => <img alt="transaction-image" height="25" width="25" src={Images.Chargebacks} />,
            },
            {
                id: 4,
                title: "Suspicious",
                to: "/suspicious-transactions",
                icon: () => <img alt="transaction-image" height="25" width="25" src={Images.Suspicious} />,
            },
            {
                id: 5,
                title: "Remove Suspicious",
                to: "/remove-suspicious-transactions",
                icon: () => <img alt="transaction-image" height="25" width="25" src={Images.RemoveSuspicious} />,
            },
            {
                id: 6,
                title: "Test Transactions",
                to: "/test-transactions",
                icon: () => <img alt="transaction-image" height="25" width="25" src={Images.TestTransactions} />,
            },
        ],
        isAuthRequired: true,
        header: true,
        menu: true,
    },
    {
        id: 5,
        icon: () => <Icon.CreditCard size={20} />,
        title: "Payment Method",
        // to: ["/pay-button-list", "/invoice", "/"],
        totalRoute: [
            "/payment-links",
            "/payment-links/create",
            "/payment-links/edit/:id",
        ],
        type: menuElementsType.MULTI,
        subMenuItems: [
            {
                id: 1,
                title: "Payment Links",
                to: "/payment-links",
                icon: () => <Icon.Link size={20} />,
            },
        ],
        isAuthRequired: true,
        header: true,
        menu: true,
    },
    {
        id: 6,
        icon: () => <img height="25" width="25" src={Images.Payout} />,
        title: "Payout Reports",
        // to: ["/pay-button-list", "/invoice", "/"],
        totalRoute: ["/auto-payout-report", "/default-payout-report", "/default-payout-report/:connectorId"],
        type: menuElementsType.MULTI,
        subMenuItems: [
            {
                id: 1,
                title: "Auto Payout",
                to: "/auto-payout-report",
                icon: () => <img height="25" width="25" src={Images.AutoPayoutReports} />,
            },
            {
                id: 2,
                title: "Default Payout",
                to: "/default-payout-report",
                icon: () => <img height="25" width="25" src={Images.DefaultPayoutReports} />,
            },
        ],
        isAuthRequired: true,
        header: true,
        menu: true,
    },
    {
        id: 7,
        // to: "/store-front",
        totalRoute: [
            "/ip-whitelist",
            "/ip-whitelist/create",
            "/ip-whitelist/:ipwhitelist/edit",
            "/rules",
            "/rules/create",
            "/api-document",
            "/api-document/:id",
            "/api-key",
            "/rules/edit/:rulesId",
            "/webhook",
            "/webhook/create",
            "/webhook/update/:webhookId",
            "/webhook/view/:webhookId",
        ],
        icon: () => <Icon.Code />,
        title: "Developer",
        type: menuElementsType.MULTI,
        subMenuItems: [
            {
                id: 1,
                title: "Rules",
                to: "/rules",
                icon: () => <img src={Images.Rules} height="25" width="25" />,
            },
            {
                id: 2,
                title: "IP Whitelist",
                to: "/ip-whitelist",
                icon: () => <Icon.Lock size={20} />,
            },
            {
                id: 3,
                title: "API KEY",
                to: "/api-key",
                icon: () => <Icon.Key size={20} />,
            },
            {
                id: 4,
                title: "Webhook",
                to: "/webhook",
                icon: () => <img src={Images.Webhook} height="25" width="25" />,
            },
            // {
            //     id: 5,
            //     title: "Documentation",
            //     to: "/api-document",
            //     icon: () => <img src={Images.Documentation} height="25" width="25" />,
            // },
        ],
        isAuthRequired: true,
        header: true,
        menu: true,
    },
    {
        id: 10,
        totalRoute: ["/profile", "/notifications", "/notification/detail/:notificationId", "/privacy-policy", "/terms-and-conditions"],
        icon: () => <Icon.Code />,
        title: "Developer",
        type: menuElementsType.NONE,
        isAuthRequired: true,
        header: true,
        menu: true,
    },
    // {
    //     id: 1,
    //     to: "/",
    //     totalRoute: ["/"],
    //     icon: () => <Icon.Home size={20} />,
    //     title: "Dashboard",
    //     type: menuElementsType.SINGLE,
    //     isAuthRequired: true,
    //     header: true,
    //     menu: true,
    // },
];

export const applicationKey = {
    company_name: { value: "Company Name" },
    company_registration_num: { value: "Company Registration Number" },
    company_year_of_register: { value: "Company Year of Registration" },
    country_registration: { value: "Company Registration Country" },
    categories: { value: "Categories" },
    company_roc: { value: "Certificate of Incorporation (ROC)", isDocumentType: true },
    company_gst_num: { value: "Company GST Number" },
    company_address: { value: "Company Address" },
    company_latest_bank_statement: { value: "Bank Statement", isDocumentType: true },
    business_activity: { value: "Business Domain" },
    website: { value: "Website" },
    director_name: { value: "Name" },
    director_address: { value: "Address" },
    director_email: { value: "Email" },
    director_phone_num: { value: "Phone Number" },
    director_pan_card: { value: "Pan Card", isDocumentType: true },
    director_passport: { value: "Passport", isDocumentType: true },
    director_aadhar_card_front_image: { value: "Aadhar Card Front", isDocumentType: true },
    director_aadhar_card_back_image: { value: "Aadhar Card Back", isDocumentType: true },
    director_bank_statement: { value: "Bank Statement", isDocumentType: true },
    director_latest_utility_bill: { value: "Utility Bill", isDocumentType: true },
    director_country: { value: "Country" },
    director_articles_of_incorporation: { value: "Articles Of Incorporation", isDocumentType: true },
    director_ubo_bank_statement: { value: "UBO's Bank Statement (last 90 days)", isDocumentType: true },
    director_processing_history: { value: "Processing PreviewHistory (if any)", isDocumentType: true },
    director_memorandum_of_association: { value: "MOA (Memorandum of Association)", isDocumentType: true },
    director_additional_document: { value: "Additional Document", isDocumentType: true },
    share_holder_name: { value: "Shareholder Name" },
    share_holder_address: { value: "Shareholder Address" },
    share_holder_email: { value: "Shareholder Email" },
    share_holder_phone_num: { value: "Shareholder Phone Number" },
    share_holder_pan_card: { value: "Pan Card", isDocumentType: true },
    share_holder_passport: { value: "Passport", isDocumentType: true },
    share_holder_aadhar_card_front_image: { value: "Aadhar Card Front", isDocumentType: true },
    share_holder_aadhar_card_back_image: { value: "Aadhar Card Back", isDocumentType: true },
    share_holder_bank_statement: { value: "Bank Statement", isDocumentType: true },
    share_holder_latest_utility_bill: { value: "Utility Bill", isDocumentType: true },
    share_holder_country: { value: "Shareholder Country" },
    share_holder_articles_of_incorporation: { value: "Articles Of Incorporation", isDocumentType: true },
    share_holder_ubo_bank_statement: { value: "UBO's Bank Statement (last 90 days)", isDocumentType: true },
    share_holder_processing_history: { value: "Processing PreviewHistory (if any)", isDocumentType: true },
    share_holder_memorandum_of_association: { value: "MOA (Memorandum of Association)", isDocumentType: true },
    share_holder_additional_document: { value: "Additional Document (Multi)", isDocumentType: true },
    aadhar_card_front_image: { value: "Aadhar Card Front", isDocumentType: true },
    aadhar_card_back_image: { value: "Aadhar Card Back", isDocumentType: true },
    cancel_cheque: { value: "Cancel Cheque", isDocumentType: true },
    pan_card: { value: "Pan Card", isDocumentType: true },
    passport: { value: "Passport", isDocumentType: true },
    voter_id: { value: "Voter ID", isDocumentType: true },
    driving_license: { value: "Driving License", isDocumentType: true },
    certificate_of_incorporation: { value: "Certificate of Incorporation", isDocumentType: true },
    business_address_proof: { value: "Business Address Proof", isDocumentType: true },
    personalised_cancel_cheque_of_account: { value: "Personalised Cancel Cheque of Account", isDocumentType: true },
    memorandum_article_of_association_of_company: { value: "Memorandum Article of Association of Company", isDocumentType: true },
    board_resolution_company_stamp: { value: "Board Resolution Company Stamp", isDocumentType: true },
    beneficial_owners_declaration: { value: "Beneficial Owners Declaration", isDocumentType: true },
    gst_doc: { value: "GST Certificate", isDocumentType: true },
    registration_certificate: { value: "Registration Certificate", isDocumentType: true },
    resolution_letter: { value: "Resolution Letter", isDocumentType: true },
    llp_dead: { value: "LLP Dead", isDocumentType: true },
    moa: { value: "MOA", isDocumentType: true },
    aoa: { value: "AOA", isDocumentType: true },
    shops_and_establishment_document: { value: "Shops And Establishment Document", isDocumentType: true },
    fssai_fda_license: { value: "FSSAI FDA License", isDocumentType: true },
    udyam_certificate: { value: "Udyam Certificate", isDocumentType: true },
    trust_deed: { value: "Trust Deed", isDocumentType: true },
    itr: { value: "ITR", isDocumentType: true },
    1: {
        aadhar_card_front_image: { value: "Aadhar Card Front", isDocumentType: true },
        aadhar_card_back_image: { value: "Aadhar Card Back", isDocumentType: true },
        cancel_cheque: { value: "Cancel Cheque", isDocumentType: true },
        pan_card: { value: "Pan Card", isDocumentType: true },
        passport: { value: "Passport", isDocumentType: true },
        voter_id: { value: "Voter ID", isDocumentType: true },
        driving_license: { value: "Driving License", isDocumentType: true },
    },
    2: {
        company_name: { value: "Company Name" },
        company_year_of_register: { value: "Year of Registration" },
        country_registration: { value: "Registration Country" },
        company_registration_num: { value: "Registration Number" },
        company_gst_num: { value: "GST Number" },
        company_address: { value: "Company Address" },
        business_activity: { value: "Business Domain" },
        website: { value: "Company Website" },
        categories: { value: "Categories" },
        pan_card: { value: "Company Pan Card", isDocumentType: true },
        certificate_of_incorporation: { value: "Certificate of Incorporation", isDocumentType: true },
        business_address_proof: { value: "Business Address Proof", isDocumentType: true },
        personalised_cancel_cheque_of_account: { value: "Personalised Cancel Cheque of Account", isDocumentType: true },
        moa: { value: "Memorandum Article of Company", isDocumentType: true },
        aoa: { value: "Association of Company", isDocumentType: true },
        board_resolution_company_stamp: { value: "Board Resolution Company Stamp", isDocumentType: true },
        beneficial_owners_declaration: { value: "Beneficial Owners Declaration", isDocumentType: true },
        gst_doc: { value: "GST Certificate", isDocumentType: true },
        udyam_certificate: { value: "Udyam Certificate", isDocumentType: true },
        udyam_num: { value: "Udyam Number" },
    },
    3: {
        company_name: { value: "Company Name" },
        company_year_of_register: { value: "Year of Registration" },
        country_registration: { value: "Registration Country" },
        company_registration_num: { value: "Registration Number" },
        company_gst_num: { value: "GST Number" },
        company_address: { value: "Company Address" },
        business_activity: { value: "Business Domain" },
        website: { value: "Company Website" },
        categories: { value: "Categories" },
        pan_card: { value: "Pan card of Partnership Firm", isDocumentType: true },
        business_address_proof: { value: "Business Address Proof", isDocumentType: true },
        registration_certificate: { value: "Registration Certificate", isDocumentType: true },
        resolution_letter: {
            value: "Resolution letter on letter head making a partner as Auth signatory company if not explicity covered in the partnership deed",
            isDocumentType: true,
        },
        personalised_cancel_cheque_of_account: { value: "Personalised Cancel Cheque of Account", isDocumentType: true },
        udyam_certificate: { value: "Udyam Certificate", isDocumentType: true },
        udyam_num: { value: "Udyam Number" },
    },
    4: {
        company_name: { value: "Company Name" },
        company_year_of_register: { value: "Year of Registration" },
        country_registration: { value: "Registration Country" },
        company_registration_num: { value: "Registration Number" },
        company_gst_num: { value: "GST Number" },
        company_address: { value: "Company Address" },
        business_activity: { value: "Business Domain" },
        website: { value: "Company Website" },
        categories: { value: "Categories" },
        pan_card: { value: "Pan card of Partnership Firm", isDocumentType: true },
        certificate_of_incorporation: { value: "Certificate of incorporation for LLP", isDocumentType: true },
        llp_dead: { value: "LLP Dead", isDocumentType: true },
        moa: { value: "Memorandum Article of Company", isDocumentType: true },
        aoa: { value: "Association of Company", isDocumentType: true },
        gst_doc: { value: "GST Certificate", isDocumentType: true },
        personalised_cancel_cheque_of_account: { value: "Personalised Cancel Cheque of Account", isDocumentType: true },
        business_address_proof: { value: "Business Address Proof", isDocumentType: true },
        resolution_letter: {
            value: "Resolution letter on letter head making a partner as Auth signatory company",
            isDocumentType: true,
        },
    },
    5: {
        shops_and_establishment_document: { value: "Shops and Establishment document issued by Local Authority", isDocumentType: true },
        fssai_fda_license: { value: "FSSAI/FDA License", isDocumentType: true },
        udyam_certificate: { value: "Udyam Certificate", isDocumentType: true },
        udyam_num: { value: "Udyam Number" },
        gst_doc: { value: "GST Certificate", isDocumentType: true },
        personalised_cancel_cheque_of_account: { value: "Cancel Cheque", isDocumentType: true },
        aadhar_card_front_image: { value: "Aadhar Card Front", isDocumentType: true },
        aadhar_card_back_image: { value: "Aadhar Card Back", isDocumentType: true },
        pan_card: { value: "Pan Card", isDocumentType: true },
        passport: { value: "Passport", isDocumentType: true },
        voter_id: { value: "Voter ID", isDocumentType: true },
        driving_license: { value: "Driving License", isDocumentType: true },
        company_gst_num: { value: "GST Number" },
    },
    6: {
        company_name: { value: "Company Name" },
        company_year_of_register: { value: "Year of Registration" },
        country_registration: { value: "Registration Country" },
        company_registration_num: { value: "Registration Number" },
        company_gst_num: { value: "GST Number" },
        company_address: { value: "Company Address" },
        business_activity: { value: "Business Domain" },
        website: { value: "Company Website" },
        categories: { value: "Categories" },
        pan_card: { value: "Trust Pan Card", isDocumentType: true },
        registration_certificate: { value: "Registration Certificate of Trust", isDocumentType: true },
        trust_deed: { value: "Trust Deed", isDocumentType: true },
        business_address_proof: { value: "Business Address Proof", isDocumentType: true },
        itr: { value: "ITR for 2year", isDocumentType: true },
        gst_doc: { value: "GST Certificate", isDocumentType: true },
        personalised_cancel_cheque_of_account: { value: "Personalised Cancel Cheque of Account", isDocumentType: true },
        board_resolution_company_stamp: {
            value: "Board Resolution with trust stamp & authorised person sign on Trust letter Head",
            isDocumentType: true,
        },
    },
};