export const countryCodes = [
    {
        name: "Afghanistan",
        value: "+93",
        code: "AF",
        flag: "🇦🇫",
    },
    {
        name: "Albania",
        value: "+355",
        code: "AL",
        flag: "🇦🇱",
    },
    {
        name: "Algeria",
        value: "+213",
        code: "DZ",
        flag: "🇩🇿",
    },
    {
        name: "American Samoa",
        value: "+1684",
        code: "AS",
        flag: "🇦🇸",
    },
    {
        name: "Andorra",
        value: "+376",
        code: "AD",
        flag: "🇦🇩",
    },
    {
        name: "Angola",
        value: "+244",
        code: "AO",
        flag: "🇦🇴",
    },
    {
        name: "Anguilla",
        value: "+1264",
        code: "AI",
        flag: "🇦🇮",
    },
    {
        name: "Antarctica",
        value: "+672",
        code: "AQ",
        flag: "🇦🇶",
    },
    {
        name: "Antigua and Barbuda",
        value: "+1268",
        code: "AG",
        flag: "🇦🇬",
    },
    {
        name: "Argentina",
        value: "+54",
        code: "AR",
        flag: "🇦🇷",
    },
    {
        name: "Armenia",
        value: "+374",
        code: "AM",
        flag: "🇦🇲",
    },
    {
        name: "Aruba",
        value: "+297",
        code: "AW",
        flag: "🇦🇼",
    },
    {
        name: "Australia",
        value: "+61",
        code: "AU",
        flag: "🇦🇺",
    },
    {
        name: "Austria",
        value: "+43",
        code: "AT",
        flag: "🇦🇹",
    },
    {
        name: "Azerbaijan",
        value: "+994",
        code: "AZ",
        flag: "🇦🇿",
    },
    {
        name: "Bahamas",
        value: "+1242",
        code: "BS",
        flag: "🇧🇸",
    },
    {
        name: "Bahrain",
        value: "+973",
        code: "BH",
        flag: "🇧🇭",
    },
    {
        name: "Bangladesh",
        value: "+880",
        code: "BD",
        flag: "🇧🇩",
    },
    {
        name: "Barbados",
        value: "+1246",
        code: "BB",
        flag: "🇧🇧",
    },
    {
        name: "Belarus",
        value: "+375",
        code: "BY",
        flag: "🇧🇾",
    },
    {
        name: "Belgium",
        value: "+32",
        code: "BE",
        flag: "🇧🇪",
    },
    {
        name: "Belize",
        value: "+501",
        code: "BZ",
        flag: "🇧🇿",
    },
    {
        name: "Benin",
        value: "+229",
        code: "BJ",
        flag: "🇧🇯",
    },
    {
        name: "Bermuda",
        value: "+1441",
        code: "BM",
        flag: "🇧🇲",
    },
    {
        name: "Bhutan",
        value: "+975",
        code: "BT",
        flag: "🇧🇹",
    },
    {
        name: "Bolivia",
        value: "+591",
        code: "BO",
        flag: "🇧🇴",
    },
    {
        name: "Bosnia and Herzegovina",
        value: "+387",
        code: "BA",
        flag: "🇧🇦",
    },
    {
        name: "Botswana",
        value: "+267",
        code: "BW",
        flag: "🇧🇼",
    },
    {
        name: "Brazil",
        value: "+55",
        code: "BR",
        flag: "🇧🇷",
    },
    {
        name: "British Indian Ocean Territory",
        value: "+246",
        code: "IO",
        flag: "🇮🇴",
    },
    {
        name: "Brunei Darussalam",
        value: "+673",
        code: "BN",
        flag: "🇧🇳",
    },
    {
        name: "Bulgaria",
        value: "+359",
        code: "BG",
        flag: "🇧🇬",
    },
    {
        name: "Burkina Faso",
        value: "+226",
        code: "BF",
        flag: "🇧🇫",
    },
    {
        name: "Burundi",
        value: "+257",
        code: "BI",
        flag: "🇧🇮",
    },
    {
        name: "Cambodia",
        value: "+855",
        code: "KH",
        flag: "🇰🇭",
    },
    {
        name: "Cameroon",
        value: "+237",
        code: "CM",
        flag: "🇨🇲",
    },
    {
        name: "Canada",
        value: "+1",
        code: "CA",
        flag: "🇨🇦",
    },
    {
        name: "Cape Verde",
        value: "+238",
        code: "CV",
        flag: "🇨🇻",
    },
    {
        name: "Cayman Islands",
        value: "+345",
        code: "KY",
        flag: "🇰🇾",
    },
    {
        name: "Central African Republic",
        value: "+236",
        code: "CF",
        flag: "🇨🇫",
    },
    {
        name: "Chad",
        value: "+235",
        code: "TD",
        flag: "🇹🇩",
    },
    {
        name: "Chile",
        value: "+56",
        code: "CL",
        flag: "🇨🇱",
    },
    {
        name: "China",
        value: "+86",
        code: "CN",
        flag: "🇨🇳",
    },
    {
        name: "Christmas Island",
        value: "+61",
        code: "CX",
        flag: "🇨🇽",
    },
    {
        name: "Cocos (Keeling) Islands",
        value: "+61",
        code: "CC",
        flag: "🇨🇨",
    },
    {
        name: "Colombia",
        value: "+57",
        code: "CO",
        flag: "🇨🇴",
    },
    {
        name: "Comoros",
        value: "+269",
        code: "KM",
        flag: "🇰🇲",
    },
    {
        name: "Congo",
        value: "+242",
        code: "CG",
        flag: "🇨🇬",
    },
    {
        name: "Congo, The Democratic Republic of the",
        value: "+243",
        code: "CD",
        flag: "🇨🇩",
    },
    {
        name: "Cook Islands",
        value: "+682",
        code: "CK",
        flag: "🇨🇰",
    },
    {
        name: "Costa Rica",
        value: "+506",
        code: "CR",
        flag: "🇨🇷",
    },
    {
        name: "Cote d'Ivoire",
        value: "+225",
        code: "CI",
        flag: "🇨🇮",
    },
    {
        name: "Croatia",
        value: "+385",
        code: "HR",
        flag: "🇭🇷",
    },
    {
        name: "Cuba",
        value: "+53",
        code: "CU",
        flag: "🇨🇺",
    },
    {
        name: "Cyprus",
        value: "+537",
        code: "CY",
        flag: "🇨🇾",
    },
    {
        name: "Czech Republic",
        value: "+420",
        code: "CZ",
        flag: "🇨🇿",
    },
    {
        name: "Denmark",
        value: "+45",
        code: "DK",
        flag: "🇩🇰",
    },
    {
        name: "Djibouti",
        value: "+253",
        code: "DJ",
        flag: "🇩🇯",
    },
    {
        name: "Dominica",
        value: "+1767",
        code: "DM",
        flag: "🇩🇲",
    },
    {
        name: "Dominican Republic",
        value: "+1849",
        code: "DO",
        flag: "🇩🇴",
    },
    {
        name: "Ecuador",
        value: "+593",
        code: "EC",
        flag: "🇪🇨",
    },
    {
        name: "Egypt",
        value: "+20",
        code: "EG",
        flag: "🇪🇬",
    },
    {
        name: "El Salvador",
        value: "+503",
        code: "SV",
        flag: "🇸🇻",
    },
    {
        name: "Equatorial Guinea",
        value: "+240",
        code: "GQ",
        flag: "🇬🇶",
    },
    {
        name: "Eritrea",
        value: "+291",
        code: "ER",
        flag: "🇪🇷",
    },
    {
        name: "Estonia",
        value: "+372",
        code: "EE",
        flag: "🇪🇪",
    },
    {
        name: "Ethiopia",
        value: "+251",
        code: "ET",
        flag: "🇪🇹",
    },
    {
        name: "Falkland Islands (Malvinas)",
        value: "+500",
        code: "FK",
        flag: "🇫🇰",
    },
    {
        name: "Faroe Islands",
        value: "+298",
        code: "FO",
        flag: "🇫🇴",
    },
    {
        name: "Fiji",
        value: "+679",
        code: "FJ",
        flag: "🇫🇯",
    },
    {
        name: "Finland",
        value: "+358",
        code: "FI",
        flag: "🇫🇮",
    },
    {
        name: "France",
        value: "+33",
        code: "FR",
        flag: "🇫🇷",
    },
    {
        name: "French Guiana",
        value: "+594",
        code: "GF",
        flag: "🇬🇫",
    },
    {
        name: "French Polynesia",
        value: "+689",
        code: "PF",
        flag: "🇵🇫",
    },
    {
        name: "Gabon",
        value: "+241",
        code: "GA",
        flag: "🇬🇦",
    },
    {
        name: "Gambia",
        value: "+220",
        code: "GM",
        flag: "🇬🇲",
    },
    {
        name: "Georgia",
        value: "+995",
        code: "GE",
        flag: "🇬🇪",
    },
    {
        name: "Germany",
        value: "+49",
        code: "DE",
        flag: "🇩🇪",
    },
    {
        name: "Ghana",
        value: "+233",
        code: "GH",
        flag: "🇬🇭",
    },
    {
        name: "Gibraltar",
        value: "+350",
        code: "GI",
        flag: "🇬🇮",
    },
    {
        name: "Greece",
        value: "+30",
        code: "GR",
        flag: "🇬🇷",
    },
    {
        name: "Greenland",
        value: "+299",
        code: "GL",
        flag: "🇬🇱",
    },
    {
        name: "Grenada",
        value: "+1473",
        code: "GD",
        flag: "🇬🇩",
    },
    {
        name: "Guadeloupe",
        value: "+590",
        code: "GP",
        flag: "🇬🇵",
    },
    {
        name: "Guam",
        value: "+1671",
        code: "GU",
        flag: "🇬🇺",
    },
    {
        name: "Guatemala",
        value: "+502",
        code: "GT",
        flag: "🇬🇹",
    },
    {
        name: "Guernsey",
        value: "+44",
        code: "GG",
        flag: "🇬🇬",
    },
    {
        name: "Guinea",
        value: "+224",
        code: "GN",
        flag: "🇬🇳",
    },
    {
        name: "Guinea-Bissau",
        value: "+245",
        code: "GW",
        flag: "🇬🇼",
    },
    {
        name: "Guyana",
        value: "+595",
        code: "GY",
        flag: "🇬🇾",
    },
    {
        name: "Haiti",
        value: "+509",
        code: "HT",
        flag: "🇭🇹",
    },
    {
        name: "Holy See (Vatican City State)",
        value: "+379",
        code: "VA",
        flag: "🇻🇦",
    },
    {
        name: "Honduras",
        value: "+504",
        code: "HN",
        flag: "🇭🇳",
    },
    {
        name: "Hong Kong",
        value: "+852",
        code: "HK",
        flag: "🇭🇰",
    },
    {
        name: "Hungary",
        value: "+36",
        code: "HU",
        flag: "🇭🇺",
    },
    {
        name: "Iceland",
        value: "+354",
        code: "IS",
        flag: "🇮🇸",
    },
    {
        name: "India",
        value: "+91",
        code: "IN",
        flag: "🇮🇳",
    },
    {
        name: "Indonesia",
        value: "+62",
        code: "ID",
        flag: "🇮🇩",
    },
    {
        name: "Iran, Islamic Republic of",
        value: "+98",
        code: "IR",
        flag: "🇮🇷",
    },
    {
        name: "Iraq",
        value: "+964",
        code: "IQ",
        flag: "🇮🇶",
    },
    {
        name: "Ireland",
        value: "+353",
        code: "IE",
        flag: "🇮🇪",
    },
    {
        name: "Isle of Man",
        value: "+44",
        code: "IM",
        flag: "🇮🇲",
    },
    {
        name: "Israel",
        value: "+972",
        code: "IL",
        flag: "🇮🇱",
    },
    {
        name: "Italy",
        value: "+39",
        code: "IT",
        flag: "🇮🇹",
    },
    {
        name: "Jamaica",
        value: "+1876",
        code: "JM",
        flag: "🇯🇲",
    },
    {
        name: "Japan",
        value: "+81",
        code: "JP",
        flag: "🇯🇵",
    },
    {
        name: "Jersey",
        value: "+44",
        code: "JE",
        flag: "🇯🇪",
    },
    {
        name: "Jordan",
        value: "+962",
        code: "JO",
        flag: "🇯🇴",
    },
    {
        name: "Kazakhstan",
        value: "+77",
        code: "KZ",
        flag: "🇰🇿",
    },
    {
        name: "Kenya",
        value: "+254",
        code: "KE",
        flag: "🇰🇪",
    },
    {
        name: "Kiribati",
        value: "+686",
        code: "KI",
        flag: "🇰🇮",
    },
    {
        name: "Korea, Democratic People's Republic of",
        value: "+850",
        code: "KP",
        flag: "🇰🇵",
    },
    {
        name: "Korea, Republic of",
        value: "+82",
        code: "KR",
        flag: "🇰🇷",
    },
    {
        name: "Kuwait",
        value: "+965",
        code: "KW",
        flag: "🇰🇼",
    },
    {
        name: "Kyrgyzstan",
        value: "+996",
        code: "KG",
        flag: "🇰🇬",
    },
    {
        name: "Lao People's Democratic Republic",
        value: "+856",
        code: "LA",
        flag: "🇱🇦",
    },
    {
        name: "Latvia",
        value: "+371",
        code: "LV",
        flag: "🇱🇻",
    },
    {
        name: "Lebanon",
        value: "+961",
        code: "LB",
        flag: "🇱🇧",
    },
    {
        name: "Lesotho",
        value: "+266",
        code: "LS",
        flag: "🇱🇸",
    },
    {
        name: "Liberia",
        value: "+231",
        code: "LR",
        flag: "🇱🇷",
    },
    {
        name: "Libyan Arab Jamahiriya",
        value: "+218",
        code: "LY",
        flag: "🇱🇾",
    },
    {
        name: "Liechtenstein",
        value: "+423",
        code: "LI",
        flag: "🇱🇮",
    },
    {
        name: "Lithuania",
        value: "+370",
        code: "LT",
        flag: "🇱🇹",
    },
    {
        name: "Luxembourg",
        value: "+352",
        code: "LU",
        flag: "🇱🇺",
    },
    {
        name: "Macao",
        value: "+853",
        code: "MO",
        flag: "🇲🇴",
    },
    {
        name: "Macedonia, The Former Yugoslav Republic of",
        value: "+389",
        code: "MK",
        flag: "🇲🇰",
    },
    {
        name: "Madagascar",
        value: "+261",
        code: "MG",
        flag: "🇲🇬",
    },
    {
        name: "Malawi",
        value: "+265",
        code: "MW",
        flag: "🇲🇼",
    },
    {
        name: "Malaysia",
        value: "+60",
        code: "MY",
        flag: "🇲🇾",
    },
    {
        name: "Maldives",
        value: "+960",
        code: "MV",
        flag: "🇲🇻",
    },
    {
        name: "Mali",
        value: "+223",
        code: "ML",
        flag: "🇲🇱",
    },
    {
        name: "Malta",
        value: "+356",
        code: "MT",
        flag: "🇲🇹",
    },
    {
        name: "Marshall Islands",
        value: "+692",
        code: "MH",
        flag: "🇲🇭",
    },
    {
        name: "Martinique",
        value: "+596",
        code: "MQ",
        flag: "🇲🇶",
    },
    {
        name: "Mauritania",
        value: "+222",
        code: "MR",
        flag: "🇲🇷",
    },
    {
        name: "Mauritius",
        value: "+230",
        code: "MU",
        flag: "🇲🇺",
    },
    {
        name: "Mayotte",
        value: "+262",
        code: "YT",
        flag: "🇾🇹",
    },
    {
        name: "Mexico",
        value: "+52",
        code: "MX",
        flag: "🇲🇽",
    },
    {
        name: "Micronesia, Federated States of",
        value: "+691",
        code: "FM",
        flag: "🇫🇲",
    },
    {
        name: "Moldova, Republic of",
        value: "+373",
        code: "MD",
        flag: "🇲🇩",
    },
    {
        name: "Monaco",
        value: "+377",
        code: "MC",
        flag: "🇲🇨",
    },
    {
        name: "Mongolia",
        value: "+976",
        code: "MN",
        flag: "🇲🇳",
    },
    {
        name: "Montenegro",
        value: "+382",
        code: "ME",
        flag: "🇲🇪",
    },
    {
        name: "Montserrat",
        value: "+1664",
        code: "MS",
        flag: "🇲🇸",
    },
    {
        name: "Morocco",
        value: "+212",
        code: "MA",
        flag: "🇲🇦",
    },
    {
        name: "Mozambique",
        value: "+258",
        code: "MZ",
        flag: "🇲🇿",
    },
    {
        name: "Myanmar",
        value: "+95",
        code: "MM",
        flag: "🇲🇲",
    },
    {
        name: "Namibia",
        value: "+264",
        code: "NA",
        flag: "🇳🇦",
    },
    {
        name: "Nauru",
        value: "+674",
        code: "NR",
        flag: "🇳🇷",
    },
    {
        name: "Nepal",
        value: "+977",
        code: "NP",
        flag: "🇳🇵",
    },
    {
        name: "Netherlands",
        value: "+31",
        code: "NL",
        flag: "🇳🇱",
    },
    {
        name: "Netherlands Antilles",
        value: "+599",
        code: "AN",
        flag: "🇦🇳",
    },
    {
        name: "New Caledonia",
        value: "+687",
        code: "NC",
        flag: "🇳🇨",
    },
    {
        name: "New Zealand",
        value: "+64",
        code: "NZ",
        flag: "🇳🇿",
    },
    {
        name: "Nicaragua",
        value: "+505",
        code: "NI",
        flag: "🇳🇮",
    },
    {
        name: "Niger",
        value: "+227",
        code: "NE",
        flag: "🇳🇪",
    },
    {
        name: "Nigeria",
        value: "+234",
        code: "NG",
        flag: "🇳🇬",
    },
    {
        name: "Niue",
        value: "+683",
        code: "NU",
        flag: "🇳🇺",
    },
    {
        name: "Norfolk Island",
        value: "+672",
        code: "NF",
        flag: "🇳🇫",
    },
    {
        name: "Northern Mariana Islands",
        value: "+1670",
        code: "MP",
        flag: "🇲🇵",
    },
    {
        name: "Norway",
        value: "+47",
        code: "NO",
        flag: "🇳🇴",
    },
    {
        name: "Oman",
        value: "+968",
        code: "OM",
        flag: "🇴🇲",
    },
    {
        name: "Pakistan",
        value: "+92",
        code: "PK",
        flag: "🇵🇰",
    },
    {
        name: "Palau",
        value: "+680",
        code: "PW",
        flag: "🇵🇼",
    },
    {
        name: "Palestinian Territory, Occupied",
        value: "+970",
        code: "PS",
        flag: "🇵🇸",
    },
    {
        name: "Panama",
        value: "+507",
        code: "PA",
        flag: "🇵🇦",
    },
    {
        name: "Papua New Guinea",
        value: "+675",
        code: "PG",
        flag: "🇵🇬",
    },
    {
        name: "Paraguay",
        value: "+595",
        code: "PY",
        flag: "🇵🇾",
    },
    {
        name: "Peru",
        value: "+51",
        code: "PE",
        flag: "🇵🇪",
    },
    {
        name: "Philippines",
        value: "+63",
        code: "PH",
        flag: "🇵🇭",
    },
    {
        name: "Pitcairn",
        value: "+872",
        code: "PN",
        flag: "🇵🇳",
    },
    {
        name: "Poland",
        value: "+48",
        code: "PL",
        flag: "🇵🇱",
    },
    {
        name: "Portugal",
        value: "+351",
        code: "PT",
        flag: "🇵🇹",
    },
    {
        name: "Puerto Rico",
        value: "+1939",
        code: "PR",
        flag: "🇵🇷",
    },
    {
        name: "Qatar",
        value: "+974",
        code: "QA",
        flag: "🇶🇦",
    },
    {
        name: "Romania",
        value: "+40",
        code: "RO",
        flag: "🇷🇴",
    },
    {
        name: "Russia",
        value: "+7",
        code: "RU",
        flag: "🇷🇺",
    },
    {
        name: "Rwanda",
        value: "+250",
        code: "RW",
        flag: "🇷🇼",
    },
    {
        name: "Réunion",
        value: "+262",
        code: "RE",
        flag: "🇷🇪",
    },
    {
        name: "Saint Barthélemy",
        value: "+590",
        code: "BL",
        flag: "🇧🇱",
    },
    {
        name: "Saint Helena, Ascension and Tristan Da Cunha",
        value: "+290",
        code: "SH",
        flag: "🇸🇭",
    },
    {
        name: "Saint Kitts and Nevis",
        value: "+1869",
        code: "KN",
        flag: "🇰🇳",
    },
    {
        name: "Saint Lucia",
        value: "+1758",
        code: "LC",
        flag: "🇱🇨",
    },
    {
        name: "Saint Martin",
        value: "+590",
        code: "MF",
        flag: "🇲🇫",
    },
    {
        name: "Saint Pierre and Miquelon",
        value: "+508",
        code: "PM",
        flag: "🇵🇲",
    },
    {
        name: "Saint Vincent and the Grenadines",
        value: "+1784",
        code: "VC",
        flag: "🇻🇨",
    },
    {
        name: "Samoa",
        value: "+685",
        code: "WS",
        flag: "🇼🇸",
    },
    {
        name: "San Marino",
        value: "+378",
        code: "SM",
        flag: "🇸🇲",
    },
    {
        name: "Sao Tome and Principe",
        value: "+239",
        code: "ST",
        flag: "🇸🇹",
    },
    {
        name: "Saudi Arabia",
        value: "+966",
        code: "SA",
        flag: "🇸🇦",
    },
    {
        name: "Senegal",
        value: "+221",
        code: "SN",
        flag: "🇸🇳",
    },
    {
        name: "Serbia",
        value: "+381",
        code: "RS",
        flag: "🇷🇸",
    },
    {
        name: "Seychelles",
        value: "+248",
        code: "SC",
        flag: "🇸🇨",
    },
    {
        name: "Sierra Leone",
        value: "+232",
        code: "SL",
        flag: "🇸🇱",
    },
    {
        name: "Singapore",
        value: "+65",
        code: "SG",
        flag: "🇸🇬",
    },
    {
        name: "Slovakia",
        value: "+421",
        code: "SK",
        flag: "🇸🇰",
    },
    {
        name: "Slovenia",
        value: "+386",
        code: "SI",
        flag: "🇸🇮",
    },
    {
        name: "Solomon Islands",
        value: "+677",
        code: "SB",
        flag: "🇸🇧",
    },
    {
        name: "Somalia",
        value: "+252",
        code: "SO",
        flag: "🇸🇴",
    },
    {
        name: "South Africa",
        value: "+27",
        code: "ZA",
        flag: "🇿🇦",
    },
    {
        name: "South Georgia and the South Sandwich Islands",
        value: "+500",
        code: "GS",
        flag: "🇬🇸",
    },
    {
        name: "Spain",
        value: "+34",
        code: "ES",
        flag: "🇪🇸",
    },
    {
        name: "Sri Lanka",
        value: "+94",
        code: "LK",
        flag: "🇱🇰",
    },
    {
        name: "Sudan",
        value: "+249",
        code: "SD",
        flag: "🇸🇩",
    },
    {
        name: "Suriname",
        value: "+597",
        code: "SR",
        flag: "🇸🇷",
    },
    {
        name: "Svalbard and Jan Mayen",
        value: "+47",
        code: "SJ",
        flag: "🇸🇯",
    },
    {
        name: "Swaziland",
        value: "+268",
        code: "SZ",
        flag: "🇸🇿",
    },
    {
        name: "Sweden",
        value: "+46",
        code: "SE",
        flag: "🇸🇪",
    },
    {
        name: "Switzerland",
        value: "+41",
        code: "CH",
        flag: "🇨🇭",
    },
    {
        name: "Syrian Arab Republic",
        value: "+963",
        code: "SY",
        flag: "🇸🇾",
    },
    {
        name: "Taiwan, Province of China",
        value: "+886",
        code: "TW",
        flag: "🇹🇼",
    },
    {
        name: "Tajikistan",
        value: "+992",
        code: "TJ",
        flag: "🇹🇯",
    },
    {
        name: "Tanzania, United Republic of",
        value: "+255",
        code: "TZ",
        flag: "🇹🇿",
    },
    {
        name: "Thailand",
        value: "+66",
        code: "TH",
        flag: "🇹🇭",
    },
    {
        name: "Timor-Leste",
        value: "+670",
        code: "TL",
        flag: "🇹🇱",
    },
    {
        name: "Togo",
        value: "+228",
        code: "TG",
        flag: "🇹🇬",
    },
    {
        name: "Tokelau",
        value: "+690",
        code: "TK",
        flag: "🇹🇰",
    },
    {
        name: "Tonga",
        value: "+676",
        code: "TO",
        flag: "🇹🇴",
    },
    {
        name: "Trinidad and Tobago",
        value: "+1868",
        code: "TT",
        flag: "🇹🇹",
    },
    {
        name: "Tunisia",
        value: "+216",
        code: "TN",
        flag: "🇹🇳",
    },
    {
        name: "Turkey",
        value: "+90",
        code: "TR",
        flag: "🇹🇷",
    },
    {
        name: "Turkmenistan",
        value: "+993",
        code: "TM",
        flag: "🇹🇲",
    },
    {
        name: "Turks and Caicos Islands",
        value: "+1649",
        code: "TC",
        flag: "🇹🇨",
    },
    {
        name: "Tuvalu",
        value: "+688",
        code: "TV",
        flag: "🇹🇻",
    },
    {
        name: "Uganda",
        value: "+256",
        code: "UG",
        flag: "🇺🇬",
    },
    {
        name: "Ukraine",
        value: "+380",
        code: "UA",
        flag: "🇺🇦",
    },
    {
        name: "United Arab Emirates",
        value: "+971",
        code: "AE",
        flag: "🇦🇪",
    },
    {
        name: "United Kingdom",
        value: "+44",
        code: "GB",
        flag: "🇬🇧",
    },
    {
        name: "United States",
        value: "+1",
        code: "US",
        flag: "🇺🇸",
    },
    {
        name: "Uruguay",
        value: "+598",
        code: "UY",
        flag: "🇺🇾",
    },
    {
        name: "Uzbekistan",
        value: "+998",
        code: "UZ",
        flag: "🇺🇿",
    },
    {
        name: "Vanuatu",
        value: "+678",
        code: "VU",
        flag: "🇻🇺",
    },
    {
        name: "Venezuela, Bolivarian Republic of",
        value: "+58",
        code: "VE",
        flag: "🇻🇪",
    },
    {
        name: "Viet Nam",
        value: "+84",
        code: "VN",
        flag: "🇻🇳",
    },
    {
        name: "Virgin Islands, British",
        value: "+1284",
        code: "VG",
        flag: "🇻🇬",
    },
    {
        name: "Virgin Islands, U.S.",
        value: "+1340",
        code: "VI",
        flag: "🇻🇮",
    },
    {
        name: "Wallis and Futuna",
        value: "+681",
        code: "WF",
        flag: "🇼🇫",
    },
    {
        name: "Yemen",
        value: "+967",
        code: "YE",
        flag: "🇾🇪",
    },
    {
        name: "Zambia",
        value: "+260",
        code: "ZM",
        flag: "🇿🇲",
    },
    {
        name: "Zimbabwe",
        value: "+263",
        code: "ZW",
        flag: "🇿🇼",
    },
    {
        name: "Åland Islands",
        value: "+358",
        code: "AX",
        flag: "🇦🇽",
    },
];



export const countryCodesApplication = [
    {
        value: "Afghanistan",
        abcd: "+93",
        code: "AF",
        flag: "🇦🇫",
    },
    {
        value: "Albania",
        abcd: "+355",
        code: "AL",
        flag: "🇦🇱",
    },
    {
        value: "Algeria",
        abcd: "+213",
        code: "DZ",
        flag: "🇩🇿",
    },
    {
        value: "American Samoa",
        abcd: "+1684",
        code: "AS",
        flag: "🇦🇸",
    },
    {
        value: "Andorra",
        abcd: "+376",
        code: "AD",
        flag: "🇦🇩",
    },
    {
        value: "Angola",
        abcd: "+244",
        code: "AO",
        flag: "🇦🇴",
    },
    {
        value: "Anguilla",
        abcd: "+1264",
        code: "AI",
        flag: "🇦🇮",
    },
    {
        value: "Antarctica",
        abcd: "+672",
        code: "AQ",
        flag: "🇦🇶",
    },
    {
        value: "Antigua and Barbuda",
        abcd: "+1268",
        code: "AG",
        flag: "🇦🇬",
    },
    {
        value: "Argentina",
        abcd: "+54",
        code: "AR",
        flag: "🇦🇷",
    },
    {
        value: "Armenia",
        abcd: "+374",
        code: "AM",
        flag: "🇦🇲",
    },
    {
        value: "Aruba",
        abcd: "+297",
        code: "AW",
        flag: "🇦🇼",
    },
    {
        value: "Australia",
        abcd: "+61",
        code: "AU",
        flag: "🇦🇺",
    },
    {
        value: "Austria",
        abcd: "+43",
        code: "AT",
        flag: "🇦🇹",
    },
    {
        value: "Azerbaijan",
        abcd: "+994",
        code: "AZ",
        flag: "🇦🇿",
    },
    {
        value: "Bahamas",
        abcd: "+1242",
        code: "BS",
        flag: "🇧🇸",
    },
    {
        value: "Bahrain",
        abcd: "+973",
        code: "BH",
        flag: "🇧🇭",
    },
    {
        value: "Bangladesh",
        abcd: "+880",
        code: "BD",
        flag: "🇧🇩",
    },
    {
        value: "Barbados",
        abcd: "+1246",
        code: "BB",
        flag: "🇧🇧",
    },
    {
        value: "Belarus",
        abcd: "+375",
        code: "BY",
        flag: "🇧🇾",
    },
    {
        value: "Belgium",
        abcd: "+32",
        code: "BE",
        flag: "🇧🇪",
    },
    {
        value: "Belize",
        abcd: "+501",
        code: "BZ",
        flag: "🇧🇿",
    },
    {
        value: "Benin",
        abcd: "+229",
        code: "BJ",
        flag: "🇧🇯",
    },
    {
        value: "Bermuda",
        abcd: "+1441",
        code: "BM",
        flag: "🇧🇲",
    },
    {
        value: "Bhutan",
        abcd: "+975",
        code: "BT",
        flag: "🇧🇹",
    },
    {
        value: "Bolivia",
        abcd: "+591",
        code: "BO",
        flag: "🇧🇴",
    },
    {
        value: "Bosnia and Herzegovina",
        abcd: "+387",
        code: "BA",
        flag: "🇧🇦",
    },
    {
        value: "Botswana",
        abcd: "+267",
        code: "BW",
        flag: "🇧🇼",
    },
    {
        value: "Brazil",
        abcd: "+55",
        code: "BR",
        flag: "🇧🇷",
    },
    {
        value: "British Indian Ocean Territory",
        abcd: "+246",
        code: "IO",
        flag: "🇮🇴",
    },
    {
        value: "Brunei Darussalam",
        abcd: "+673",
        code: "BN",
        flag: "🇧🇳",
    },
    {
        value: "Bulgaria",
        abcd: "+359",
        code: "BG",
        flag: "🇧🇬",
    },
    {
        value: "Burkina Faso",
        abcd: "+226",
        code: "BF",
        flag: "🇧🇫",
    },
    {
        value: "Burundi",
        abcd: "+257",
        code: "BI",
        flag: "🇧🇮",
    },
    {
        value: "Cambodia",
        abcd: "+855",
        code: "KH",
        flag: "🇰🇭",
    },
    {
        value: "Cameroon",
        abcd: "+237",
        code: "CM",
        flag: "🇨🇲",
    },
    {
        value: "Canada",
        abcd: "+1",
        code: "CA",
        flag: "🇨🇦",
    },
    {
        value: "Cape Verde",
        abcd: "+238",
        code: "CV",
        flag: "🇨🇻",
    },
    {
        value: "Cayman Islands",
        abcd: "+345",
        code: "KY",
        flag: "🇰🇾",
    },
    {
        value: "Central African Republic",
        abcd: "+236",
        code: "CF",
        flag: "🇨🇫",
    },
    {
        value: "Chad",
        abcd: "+235",
        code: "TD",
        flag: "🇹🇩",
    },
    {
        value: "Chile",
        abcd: "+56",
        code: "CL",
        flag: "🇨🇱",
    },
    {
        value: "China",
        abcd: "+86",
        code: "CN",
        flag: "🇨🇳",
    },
    {
        value: "Christmas Island",
        abcd: "+61",
        code: "CX",
        flag: "🇨🇽",
    },
    {
        value: "Cocos (Keeling) Islands",
        abcd: "+61",
        code: "CC",
        flag: "🇨🇨",
    },
    {
        value: "Colombia",
        abcd: "+57",
        code: "CO",
        flag: "🇨🇴",
    },
    {
        value: "Comoros",
        abcd: "+269",
        code: "KM",
        flag: "🇰🇲",
    },
    {
        value: "Congo",
        abcd: "+242",
        code: "CG",
        flag: "🇨🇬",
    },
    {
        value: "Congo, The Democratic Republic of the",
        abcd: "+243",
        code: "CD",
        flag: "🇨🇩",
    },
    {
        value: "Cook Islands",
        abcd: "+682",
        code: "CK",
        flag: "🇨🇰",
    },
    {
        value: "Costa Rica",
        abcd: "+506",
        code: "CR",
        flag: "🇨🇷",
    },
    {
        value: "Cote d'Ivoire",
        abcd: "+225",
        code: "CI",
        flag: "🇨🇮",
    },
    {
        value: "Croatia",
        abcd: "+385",
        code: "HR",
        flag: "🇭🇷",
    },
    {
        value: "Cuba",
        abcd: "+53",
        code: "CU",
        flag: "🇨🇺",
    },
    {
        value: "Cyprus",
        abcd: "+537",
        code: "CY",
        flag: "🇨🇾",
    },
    {
        value: "Czech Republic",
        abcd: "+420",
        code: "CZ",
        flag: "🇨🇿",
    },
    {
        value: "Denmark",
        abcd: "+45",
        code: "DK",
        flag: "🇩🇰",
    },
    {
        value: "Djibouti",
        abcd: "+253",
        code: "DJ",
        flag: "🇩🇯",
    },
    {
        value: "Dominica",
        abcd: "+1767",
        code: "DM",
        flag: "🇩🇲",
    },
    {
        value: "Dominican Republic",
        abcd: "+1849",
        code: "DO",
        flag: "🇩🇴",
    },
    {
        value: "Ecuador",
        abcd: "+593",
        code: "EC",
        flag: "🇪🇨",
    },
    {
        value: "Egypt",
        abcd: "+20",
        code: "EG",
        flag: "🇪🇬",
    },
    {
        value: "El Salvador",
        abcd: "+503",
        code: "SV",
        flag: "🇸🇻",
    },
    {
        value: "Equatorial Guinea",
        abcd: "+240",
        code: "GQ",
        flag: "🇬🇶",
    },
    {
        value: "Eritrea",
        abcd: "+291",
        code: "ER",
        flag: "🇪🇷",
    },
    {
        value: "Estonia",
        abcd: "+372",
        code: "EE",
        flag: "🇪🇪",
    },
    {
        value: "Ethiopia",
        abcd: "+251",
        code: "ET",
        flag: "🇪🇹",
    },
    {
        value: "Falkland Islands (Malvinas)",
        abcd: "+500",
        code: "FK",
        flag: "🇫🇰",
    },
    {
        value: "Faroe Islands",
        abcd: "+298",
        code: "FO",
        flag: "🇫🇴",
    },
    {
        value: "Fiji",
        abcd: "+679",
        code: "FJ",
        flag: "🇫🇯",
    },
    {
        value: "Finland",
        abcd: "+358",
        code: "FI",
        flag: "🇫🇮",
    },
    {
        value: "France",
        abcd: "+33",
        code: "FR",
        flag: "🇫🇷",
    },
    {
        value: "French Guiana",
        abcd: "+594",
        code: "GF",
        flag: "🇬🇫",
    },
    {
        value: "French Polynesia",
        abcd: "+689",
        code: "PF",
        flag: "🇵🇫",
    },
    {
        value: "Gabon",
        abcd: "+241",
        code: "GA",
        flag: "🇬🇦",
    },
    {
        value: "Gambia",
        abcd: "+220",
        code: "GM",
        flag: "🇬🇲",
    },
    {
        value: "Georgia",
        abcd: "+995",
        code: "GE",
        flag: "🇬🇪",
    },
    {
        value: "Germany",
        abcd: "+49",
        code: "DE",
        flag: "🇩🇪",
    },
    {
        value: "Ghana",
        abcd: "+233",
        code: "GH",
        flag: "🇬🇭",
    },
    {
        value: "Gibraltar",
        abcd: "+350",
        code: "GI",
        flag: "🇬🇮",
    },
    {
        value: "Greece",
        abcd: "+30",
        code: "GR",
        flag: "🇬🇷",
    },
    {
        value: "Greenland",
        abcd: "+299",
        code: "GL",
        flag: "🇬🇱",
    },
    {
        value: "Grenada",
        abcd: "+1473",
        code: "GD",
        flag: "🇬🇩",
    },
    {
        value: "Guadeloupe",
        abcd: "+590",
        code: "GP",
        flag: "🇬🇵",
    },
    {
        value: "Guam",
        abcd: "+1671",
        code: "GU",
        flag: "🇬🇺",
    },
    {
        value: "Guatemala",
        abcd: "+502",
        code: "GT",
        flag: "🇬🇹",
    },
    {
        value: "Guernsey",
        abcd: "+44",
        code: "GG",
        flag: "🇬🇬",
    },
    {
        value: "Guinea",
        abcd: "+224",
        code: "GN",
        flag: "🇬🇳",
    },
    {
        value: "Guinea-Bissau",
        abcd: "+245",
        code: "GW",
        flag: "🇬🇼",
    },
    {
        value: "Guyana",
        abcd: "+595",
        code: "GY",
        flag: "🇬🇾",
    },
    {
        value: "Haiti",
        abcd: "+509",
        code: "HT",
        flag: "🇭🇹",
    },
    {
        value: "Holy See (Vatican City State)",
        abcd: "+379",
        code: "VA",
        flag: "🇻🇦",
    },
    {
        value: "Honduras",
        abcd: "+504",
        code: "HN",
        flag: "🇭🇳",
    },
    {
        value: "Hong Kong",
        abcd: "+852",
        code: "HK",
        flag: "🇭🇰",
    },
    {
        value: "Hungary",
        abcd: "+36",
        code: "HU",
        flag: "🇭🇺",
    },
    {
        value: "Iceland",
        abcd: "+354",
        code: "IS",
        flag: "🇮🇸",
    },
    {
        value: "India",
        abcd: "+91",
        code: "IN",
        flag: "🇮🇳",
    },
    {
        value: "Indonesia",
        abcd: "+62",
        code: "ID",
        flag: "🇮🇩",
    },
    {
        value: "Iran, Islamic Republic of",
        abcd: "+98",
        code: "IR",
        flag: "🇮🇷",
    },
    {
        value: "Iraq",
        abcd: "+964",
        code: "IQ",
        flag: "🇮🇶",
    },
    {
        value: "Ireland",
        abcd: "+353",
        code: "IE",
        flag: "🇮🇪",
    },
    {
        value: "Isle of Man",
        abcd: "+44",
        code: "IM",
        flag: "🇮🇲",
    },
    {
        value: "Israel",
        abcd: "+972",
        code: "IL",
        flag: "🇮🇱",
    },
    {
        value: "Italy",
        abcd: "+39",
        code: "IT",
        flag: "🇮🇹",
    },
    {
        value: "Jamaica",
        abcd: "+1876",
        code: "JM",
        flag: "🇯🇲",
    },
    {
        value: "Japan",
        abcd: "+81",
        code: "JP",
        flag: "🇯🇵",
    },
    {
        value: "Jersey",
        abcd: "+44",
        code: "JE",
        flag: "🇯🇪",
    },
    {
        value: "Jordan",
        abcd: "+962",
        code: "JO",
        flag: "🇯🇴",
    },
    {
        value: "Kazakhstan",
        abcd: "+77",
        code: "KZ",
        flag: "🇰🇿",
    },
    {
        value: "Kenya",
        abcd: "+254",
        code: "KE",
        flag: "🇰🇪",
    },
    {
        value: "Kiribati",
        abcd: "+686",
        code: "KI",
        flag: "🇰🇮",
    },
    {
        value: "Korea, Democratic People's Republic of",
        abcd: "+850",
        code: "KP",
        flag: "🇰🇵",
    },
    {
        value: "Korea, Republic of",
        abcd: "+82",
        code: "KR",
        flag: "🇰🇷",
    },
    {
        value: "Kuwait",
        abcd: "+965",
        code: "KW",
        flag: "🇰🇼",
    },
    {
        value: "Kyrgyzstan",
        abcd: "+996",
        code: "KG",
        flag: "🇰🇬",
    },
    {
        value: "Lao People's Democratic Republic",
        abcd: "+856",
        code: "LA",
        flag: "🇱🇦",
    },
    {
        value: "Latvia",
        abcd: "+371",
        code: "LV",
        flag: "🇱🇻",
    },
    {
        value: "Lebanon",
        abcd: "+961",
        code: "LB",
        flag: "🇱🇧",
    },
    {
        value: "Lesotho",
        abcd: "+266",
        code: "LS",
        flag: "🇱🇸",
    },
    {
        value: "Liberia",
        abcd: "+231",
        code: "LR",
        flag: "🇱🇷",
    },
    {
        value: "Libyan Arab Jamahiriya",
        abcd: "+218",
        code: "LY",
        flag: "🇱🇾",
    },
    {
        value: "Liechtenstein",
        abcd: "+423",
        code: "LI",
        flag: "🇱🇮",
    },
    {
        value: "Lithuania",
        abcd: "+370",
        code: "LT",
        flag: "🇱🇹",
    },
    {
        value: "Luxembourg",
        abcd: "+352",
        code: "LU",
        flag: "🇱🇺",
    },
    {
        value: "Macao",
        abcd: "+853",
        code: "MO",
        flag: "🇲🇴",
    },
    {
        value: "Macedonia, The Former Yugoslav Republic of",
        abcd: "+389",
        code: "MK",
        flag: "🇲🇰",
    },
    {
        value: "Madagascar",
        abcd: "+261",
        code: "MG",
        flag: "🇲🇬",
    },
    {
        value: "Malawi",
        abcd: "+265",
        code: "MW",
        flag: "🇲🇼",
    },
    {
        value: "Malaysia",
        abcd: "+60",
        code: "MY",
        flag: "🇲🇾",
    },
    {
        value: "Maldives",
        abcd: "+960",
        code: "MV",
        flag: "🇲🇻",
    },
    {
        value: "Mali",
        abcd: "+223",
        code: "ML",
        flag: "🇲🇱",
    },
    {
        value: "Malta",
        abcd: "+356",
        code: "MT",
        flag: "🇲🇹",
    },
    {
        value: "Marshall Islands",
        abcd: "+692",
        code: "MH",
        flag: "🇲🇭",
    },
    {
        value: "Martinique",
        abcd: "+596",
        code: "MQ",
        flag: "🇲🇶",
    },
    {
        value: "Mauritania",
        abcd: "+222",
        code: "MR",
        flag: "🇲🇷",
    },
    {
        value: "Mauritius",
        abcd: "+230",
        code: "MU",
        flag: "🇲🇺",
    },
    {
        value: "Mayotte",
        abcd: "+262",
        code: "YT",
        flag: "🇾🇹",
    },
    {
        value: "Mexico",
        abcd: "+52",
        code: "MX",
        flag: "🇲🇽",
    },
    {
        value: "Micronesia, Federated States of",
        abcd: "+691",
        code: "FM",
        flag: "🇫🇲",
    },
    {
        value: "Moldova, Republic of",
        abcd: "+373",
        code: "MD",
        flag: "🇲🇩",
    },
    {
        value: "Monaco",
        abcd: "+377",
        code: "MC",
        flag: "🇲🇨",
    },
    {
        value: "Mongolia",
        abcd: "+976",
        code: "MN",
        flag: "🇲🇳",
    },
    {
        value: "Montenegro",
        abcd: "+382",
        code: "ME",
        flag: "🇲🇪",
    },
    {
        value: "Montserrat",
        abcd: "+1664",
        code: "MS",
        flag: "🇲🇸",
    },
    {
        value: "Morocco",
        abcd: "+212",
        code: "MA",
        flag: "🇲🇦",
    },
    {
        value: "Mozambique",
        abcd: "+258",
        code: "MZ",
        flag: "🇲🇿",
    },
    {
        value: "Myanmar",
        abcd: "+95",
        code: "MM",
        flag: "🇲🇲",
    },
    {
        value: "Namibia",
        abcd: "+264",
        code: "NA",
        flag: "🇳🇦",
    },
    {
        value: "Nauru",
        abcd: "+674",
        code: "NR",
        flag: "🇳🇷",
    },
    {
        value: "Nepal",
        abcd: "+977",
        code: "NP",
        flag: "🇳🇵",
    },
    {
        value: "Netherlands",
        abcd: "+31",
        code: "NL",
        flag: "🇳🇱",
    },
    {
        value: "Netherlands Antilles",
        abcd: "+599",
        code: "AN",
        flag: "🇦🇳",
    },
    {
        value: "New Caledonia",
        abcd: "+687",
        code: "NC",
        flag: "🇳🇨",
    },
    {
        value: "New Zealand",
        abcd: "+64",
        code: "NZ",
        flag: "🇳🇿",
    },
    {
        value: "Nicaragua",
        abcd: "+505",
        code: "NI",
        flag: "🇳🇮",
    },
    {
        value: "Niger",
        abcd: "+227",
        code: "NE",
        flag: "🇳🇪",
    },
    {
        value: "Nigeria",
        abcd: "+234",
        code: "NG",
        flag: "🇳🇬",
    },
    {
        value: "Niue",
        abcd: "+683",
        code: "NU",
        flag: "🇳🇺",
    },
    {
        value: "Norfolk Island",
        abcd: "+672",
        code: "NF",
        flag: "🇳🇫",
    },
    {
        value: "Northern Mariana Islands",
        abcd: "+1670",
        code: "MP",
        flag: "🇲🇵",
    },
    {
        value: "Norway",
        abcd: "+47",
        code: "NO",
        flag: "🇳🇴",
    },
    {
        value: "Oman",
        abcd: "+968",
        code: "OM",
        flag: "🇴🇲",
    },
    {
        value: "Pakistan",
        abcd: "+92",
        code: "PK",
        flag: "🇵🇰",
    },
    {
        value: "Palau",
        abcd: "+680",
        code: "PW",
        flag: "🇵🇼",
    },
    {
        value: "Palestinian Territory, Occupied",
        abcd: "+970",
        code: "PS",
        flag: "🇵🇸",
    },
    {
        value: "Panama",
        abcd: "+507",
        code: "PA",
        flag: "🇵🇦",
    },
    {
        value: "Papua New Guinea",
        abcd: "+675",
        code: "PG",
        flag: "🇵🇬",
    },
    {
        value: "Paraguay",
        abcd: "+595",
        code: "PY",
        flag: "🇵🇾",
    },
    {
        value: "Peru",
        abcd: "+51",
        code: "PE",
        flag: "🇵🇪",
    },
    {
        value: "Philippines",
        abcd: "+63",
        code: "PH",
        flag: "🇵🇭",
    },
    {
        value: "Pitcairn",
        abcd: "+872",
        code: "PN",
        flag: "🇵🇳",
    },
    {
        value: "Poland",
        abcd: "+48",
        code: "PL",
        flag: "🇵🇱",
    },
    {
        value: "Portugal",
        abcd: "+351",
        code: "PT",
        flag: "🇵🇹",
    },
    {
        value: "Puerto Rico",
        abcd: "+1939",
        code: "PR",
        flag: "🇵🇷",
    },
    {
        value: "Qatar",
        abcd: "+974",
        code: "QA",
        flag: "🇶🇦",
    },
    {
        value: "Romania",
        abcd: "+40",
        code: "RO",
        flag: "🇷🇴",
    },
    {
        value: "Russia",
        abcd: "+7",
        code: "RU",
        flag: "🇷🇺",
    },
    {
        value: "Rwanda",
        abcd: "+250",
        code: "RW",
        flag: "🇷🇼",
    },
    {
        value: "Réunion",
        abcd: "+262",
        code: "RE",
        flag: "🇷🇪",
    },
    {
        value: "Saint Barthélemy",
        abcd: "+590",
        code: "BL",
        flag: "🇧🇱",
    },
    {
        value: "Saint Helena, Ascension and Tristan Da Cunha",
        abcd: "+290",
        code: "SH",
        flag: "🇸🇭",
    },
    {
        value: "Saint Kitts and Nevis",
        abcd: "+1869",
        code: "KN",
        flag: "🇰🇳",
    },
    {
        value: "Saint Lucia",
        abcd: "+1758",
        code: "LC",
        flag: "🇱🇨",
    },
    {
        value: "Saint Martin",
        abcd: "+590",
        code: "MF",
        flag: "🇲🇫",
    },
    {
        value: "Saint Pierre and Miquelon",
        abcd: "+508",
        code: "PM",
        flag: "🇵🇲",
    },
    {
        value: "Saint Vincent and the Grenadines",
        abcd: "+1784",
        code: "VC",
        flag: "🇻🇨",
    },
    {
        value: "Samoa",
        abcd: "+685",
        code: "WS",
        flag: "🇼🇸",
    },
    {
        value: "San Marino",
        abcd: "+378",
        code: "SM",
        flag: "🇸🇲",
    },
    {
        value: "Sao Tome and Principe",
        abcd: "+239",
        code: "ST",
        flag: "🇸🇹",
    },
    {
        value: "Saudi Arabia",
        abcd: "+966",
        code: "SA",
        flag: "🇸🇦",
    },
    {
        value: "Senegal",
        abcd: "+221",
        code: "SN",
        flag: "🇸🇳",
    },
    {
        value: "Serbia",
        abcd: "+381",
        code: "RS",
        flag: "🇷🇸",
    },
    {
        value: "Seychelles",
        abcd: "+248",
        code: "SC",
        flag: "🇸🇨",
    },
    {
        value: "Sierra Leone",
        abcd: "+232",
        code: "SL",
        flag: "🇸🇱",
    },
    {
        value: "Singapore",
        abcd: "+65",
        code: "SG",
        flag: "🇸🇬",
    },
    {
        value: "Slovakia",
        abcd: "+421",
        code: "SK",
        flag: "🇸🇰",
    },
    {
        value: "Slovenia",
        abcd: "+386",
        code: "SI",
        flag: "🇸🇮",
    },
    {
        value: "Solomon Islands",
        abcd: "+677",
        code: "SB",
        flag: "🇸🇧",
    },
    {
        value: "Somalia",
        abcd: "+252",
        code: "SO",
        flag: "🇸🇴",
    },
    {
        value: "South Africa",
        abcd: "+27",
        code: "ZA",
        flag: "🇿🇦",
    },
    {
        value: "South Georgia and the South Sandwich Islands",
        abcd: "+500",
        code: "GS",
        flag: "🇬🇸",
    },
    {
        value: "Spain",
        abcd: "+34",
        code: "ES",
        flag: "🇪🇸",
    },
    {
        value: "Sri Lanka",
        abcd: "+94",
        code: "LK",
        flag: "🇱🇰",
    },
    {
        value: "Sudan",
        abcd: "+249",
        code: "SD",
        flag: "🇸🇩",
    },
    {
        value: "Suriname",
        abcd: "+597",
        code: "SR",
        flag: "🇸🇷",
    },
    {
        value: "Svalbard and Jan Mayen",
        abcd: "+47",
        code: "SJ",
        flag: "🇸🇯",
    },
    {
        value: "Swaziland",
        abcd: "+268",
        code: "SZ",
        flag: "🇸🇿",
    },
    {
        value: "Sweden",
        abcd: "+46",
        code: "SE",
        flag: "🇸🇪",
    },
    {
        value: "Switzerland",
        abcd: "+41",
        code: "CH",
        flag: "🇨🇭",
    },
    {
        value: "Syrian Arab Republic",
        abcd: "+963",
        code: "SY",
        flag: "🇸🇾",
    },
    {
        value: "Taiwan, Province of China",
        abcd: "+886",
        code: "TW",
        flag: "🇹🇼",
    },
    {
        value: "Tajikistan",
        abcd: "+992",
        code: "TJ",
        flag: "🇹🇯",
    },
    {
        value: "Tanzania, United Republic of",
        abcd: "+255",
        code: "TZ",
        flag: "🇹🇿",
    },
    {
        value: "Thailand",
        abcd: "+66",
        code: "TH",
        flag: "🇹🇭",
    },
    {
        value: "Timor-Leste",
        abcd: "+670",
        code: "TL",
        flag: "🇹🇱",
    },
    {
        value: "Togo",
        abcd: "+228",
        code: "TG",
        flag: "🇹🇬",
    },
    {
        value: "Tokelau",
        abcd: "+690",
        code: "TK",
        flag: "🇹🇰",
    },
    {
        value: "Tonga",
        abcd: "+676",
        code: "TO",
        flag: "🇹🇴",
    },
    {
        value: "Trinidad and Tobago",
        abcd: "+1868",
        code: "TT",
        flag: "🇹🇹",
    },
    {
        value: "Tunisia",
        abcd: "+216",
        code: "TN",
        flag: "🇹🇳",
    },
    {
        value: "Turkey",
        abcd: "+90",
        code: "TR",
        flag: "🇹🇷",
    },
    {
        value: "Turkmenistan",
        abcd: "+993",
        code: "TM",
        flag: "🇹🇲",
    },
    {
        value: "Turks and Caicos Islands",
        abcd: "+1649",
        code: "TC",
        flag: "🇹🇨",
    },
    {
        value: "Tuvalu",
        abcd: "+688",
        code: "TV",
        flag: "🇹🇻",
    },
    {
        value: "Uganda",
        abcd: "+256",
        code: "UG",
        flag: "🇺🇬",
    },
    {
        value: "Ukraine",
        abcd: "+380",
        code: "UA",
        flag: "🇺🇦",
    },
    {
        value: "United Arab Emirates",
        abcd: "+971",
        code: "AE",
        flag: "🇦🇪",
    },
    {
        value: "United Kingdom",
        abcd: "+44",
        code: "GB",
        flag: "🇬🇧",
    },
    {
        value: "United States",
        abcd: "+1",
        code: "US",
        flag: "🇺🇸",
    },
    {
        value: "Uruguay",
        abcd: "+598",
        code: "UY",
        flag: "🇺🇾",
    },
    {
        value: "Uzbekistan",
        abcd: "+998",
        code: "UZ",
        flag: "🇺🇿",
    },
    {
        value: "Vanuatu",
        abcd: "+678",
        code: "VU",
        flag: "🇻🇺",
    },
    {
        value: "Venezuela, Bolivarian Republic of",
        abcd: "+58",
        code: "VE",
        flag: "🇻🇪",
    },
    {
        value: "Viet Nam",
        abcd: "+84",
        code: "VN",
        flag: "🇻🇳",
    },
    {
        value: "Virgin Islands, British",
        abcd: "+1284",
        code: "VG",
        flag: "🇻🇬",
    },
    {
        value: "Virgin Islands, U.S.",
        abcd: "+1340",
        code: "VI",
        flag: "🇻🇮",
    },
    {
        value: "Wallis and Futuna",
        abcd: "+681",
        code: "WF",
        flag: "🇼🇫",
    },
    {
        value: "Yemen",
        abcd: "+967",
        code: "YE",
        flag: "🇾🇪",
    },
    {
        value: "Zambia",
        abcd: "+260",
        code: "ZM",
        flag: "🇿🇲",
    },
    {
        value: "Zimbabwe",
        abcd: "+263",
        code: "ZW",
        flag: "🇿🇼",
    },
    {
        value: "Åland Islands",
        abcd: "+358",
        code: "AX",
        flag: "🇦🇽",
    },
];