export const ADD_INVOICE_REQUEST = "ADD_INVOICE_REQUEST";
export const ADD_INVOICE_RESPONSE = "ADD_INVOICE_RESPONSE";

export const EDIT_INVOICE_REQUEST = "EDIT_INVOICE_REQUEST";
export const EDIT_INVOICE_RESPONSE = "EDIT_INVOICE_RESPONSE";

export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_RESPONSE = "DELETE_INVOICE_RESPONSE";

export const LIST_INVOICE_REQUEST = "LIST_INVOICE_REQUEST";
export const LIST_INVOICE_RESPONSE = "LIST_INVOICE_RESPONSE";

export const DETAIL_INVOICE_REQUEST = "DETAIL_INVOICE_REQUEST";
export const DETAIL_INVOICE_RESPONSE = "DETAIL_INVOICE_RESPONSE";

export const SET_SEND_INVOICE_REQUEST = "SET_SEND_INVOICE_REQUEST";
export const SET_SEND_INVOICE_RESPONSE = "SET_SEND_INVOICE_RESPONSE";
