export const ADD_PAY_BUTTON_REQUEST = "ADD_PAY_BUTTON_REQUEST";
export const ADD_PAY_BUTTON_RESPONSE = "ADD_PAY_BUTTON_RESPONSE";

export const EDIT_PAY_BUTTON_REQUEST = "EDIT_PAY_BUTTON_REQUEST";
export const EDIT_PAY_BUTTON_RESPONSE = "EDIT_PAY_BUTTON_RESPONSE";

export const DELETE_PAY_BUTTON_REQUEST = "DELETE_PAY_BUTTON_REQUEST";
export const DELETE_PAY_BUTTON_RESPONSE = "DELETE_PAY_BUTTON_RESPONSE";

export const LIST_PAY_BUTTON_REQUEST = "LIST_PAY_BUTTON_REQUEST";
export const LIST_PAY_BUTTON_RESPONSE = "LIST_PAY_BUTTON_RESPONSE";

export const DETAIL_PAY_BUTTON_REQUEST = "DETAIL_PAY_BUTTON_REQUEST";
export const DETAIL_PAY_BUTTON_RESPONSE = "DETAIL_PAY_BUTTON_RESPONSE";
