export const ADD_SMS_TEMPLATE_REQUEST = "ADD_SMS_TEMPLATE_REQUEST";
export const ADD_SMS_TEMPLATE_RESPONSE = "ADD_SMS_TEMPLATE_RESPONSE";

export const EDIT_SMS_TEMPLATE_REQUEST = "EDIT_SMS_TEMPLATE_REQUEST";
export const EDIT_SMS_TEMPLATE_RESPONSE = "EDIT_SMS_TEMPLATE_RESPONSE";

export const DELETE_SMS_TEMPLATE_REQUEST = "DELETE_SMS_TEMPLATE_REQUEST";
export const DELETE_SMS_TEMPLATE_RESPONSE = "DELETE_SMS_TEMPLATE_RESPONSE";

export const LIST_SMS_TEMPLATE_REQUEST = "LIST_SMS_TEMPLATE_REQUEST";
export const LIST_SMS_TEMPLATE_RESPONSE = "LIST_SMS_TEMPLATE_RESPONSE";

export const DETAIL_SMS_TEMPLATE_REQUEST = "DETAIL_SMS_TEMPLATE_REQUEST";
export const DETAIL_SMS_TEMPLATE_RESPONSE = "DETAIL_SMS_TEMPLATE_RESPONSE";

export const LIST_MASTER_SMS_TEMPLATE_REQUEST = "LIST_MASTER_SMS_TEMPLATE_REQUEST";
export const LIST_MASTER_SMS_TEMPLATE_RESPONSE = "LIST_MASTER_SMS_TEMPLATE_RESPONSE";

export const SEND_PAYMENT_SMS_REQUEST = "SEND_PAYMENT_SMS_REQUEST";
export const SEND_PAYMENT_SMS_RESPONSE = "SEND_PAYMENT_SMS_RESPONSE";

export const SET_SEND_PAYMENT_SMS_REQUEST = "SET_SEND_PAYMENT_SMS_REQUEST";
export const SET_SEND_PAYMENT_SMS_RESPONSE = "SET_SEND_PAYMENT_SMS_RESPONSE";
