export const STEP_CHANGE_REQUEST = "STEP_CHANGE_REQUEST";
export const STEP_CHANGE_RESPONSE = "STEP_CHANGE_RESPONSE";

export const STEP_CURRENT_CHANGE_REQUEST = "STEP_CURRENT_CHANGE_REQUEST";
export const STEP_CURRENT_CHANGE_RESPONSE = "STEP_CURRENT_CHANGE_RESPONSE";

export const SET_DEFAULT_STEP_REQUEST = "SET_DEFAULT_STEP_REQUEST";
export const SET_DEFAULT_STEP_RESPONSE = "SET_DEFAULT_STEP_RESPONSE";
